data = {
  Items: [
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.PageDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 1,
      Bindings: "10001",
      RefreshInterval: 3600000,
      CustomProperties: {
        assetId: "DefaultAssetId",
        assetName: "DefaultAssetName",
        assetType: "DefaultAssetType",
      },
      DisplayFileSyncId: "UISVR@2022-09-01T09:55:51",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 3,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10003",
      ItemName: "5SUMMARY.TOTAL_MONTH.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.TimeDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 2,
      ParentDataObjectId: 1,
      Bindings: "10002",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      StartTime: "NOW-8H",
      EndTime: "NOW",
      CurrentTime: {
        Value: null,
      },
      ResampleInterval: "5 S",
      MinConfidence: "0",
      RefreshInterval: 5000,
      IsPrimaryTimeDataObject: true,
      NullValueReplace: "??????",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 4,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10004",
      ItemName: "5SUMMARY.TOTAL_DAY.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 5,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10005",
      ItemName: "5SUMMARY.TOTAL_LAST_DAY.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 6,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10006",
      ItemName: "DCS_BALE_CM1.FORECAST",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 7,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10007",
      ItemName: "5PRODUCT.SPEEDDAY.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 8,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10008",
      ItemName: "5PRODUCT.INSTANT.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 9,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10009",
      ItemName: "5AXS2004.QCS_B_WEIGHT.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 10,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10010",
      ItemName: "5AM474M01.ACTUAL_SPEED.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 11,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10011",
      ItemName: "5AXS2004.QCS_Moisture.pv",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      MinConfidence: "-10",
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 12,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10012",
      ItemName: "DCS_BALE_CM2.BY036.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 13,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10013",
      ItemName: "2AUI0016.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 14,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10014",
      ItemName: "2AUI0016.DACA.PV_CORRECT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 15,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10015",
      ItemName: "2BUI0013.PRODUCTION.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 16,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10016",
      ItemName: "2BUI0207.PRODUCTION.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 17,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10017",
      ItemName: "2CUI0016.PRODUCTION.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 18,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10018",
      ItemName: "5SUMMARY.TOTAL_MONTH_PREV.PV_INT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 19,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10019",
      ItemName: "8BDEH.DACA1.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 20,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10020",
      ItemName: "9CSHM3_CM01.GAS_CN1_W6.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 21,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10021",
      ItemName: "8AFIQ0028.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 22,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10022",
      ItemName: "6Bfiz2116.DACB.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 23,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10023",
      ItemName: "6ADI712.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      MinConfidence: "-10",
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 24,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10024",
      ItemName: "8Bfirq0071.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 25,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10025",
      ItemName: "15AFIQ0008.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 26,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10026",
      ItemName: "110KV_ENERGY.DIVA.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 27,
      ServerBehaviors: 3,
      ParentDataObjectId: 2,
      Bindings: "10027",
      ItemName: "2BLI0003.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 28,
      ServerBehaviors: 3,
      ParentDataObjectId: 2,
      Bindings: "10028",
      ItemName: "2CLI0006.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 29,
      ServerBehaviors: 3,
      ParentDataObjectId: 2,
      Bindings: "10029",
      ItemName: "5ALI0037.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 30,
      ServerBehaviors: 3,
      ParentDataObjectId: 2,
      Bindings: "10030",
      ItemName: "5ALI0054.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 31,
      ServerBehaviors: 3,
      ParentDataObjectId: 2,
      Bindings: "10031",
      ItemName: "5ALI0075.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 32,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10032",
      ItemName: "DCS_BALE_CM1.FORECAST_DAY",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 33,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10033",
      ItemName: "2BLI0003.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 34,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10034",
      ItemName: "2CLI0006.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 35,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10035",
      ItemName: "5ALI0037.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 36,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10036",
      ItemName: "5ALI0054.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 37,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10037",
      ItemName: "5ALI0075.DACA.PV",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 38,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10038",
      ItemName: "1PRODUCT.PLOT_M3_1.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 0,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 39,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10039",
      ItemName: "1PRODUCT.PLOT_M3_2.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 40,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10040",
      ItemName: "1PRODUCT.PROCENT_2.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 41,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10041",
      ItemName: "5PRODUCT.CURR_SHIFT.PV",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 0,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 42,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10042",
      ItemName: "CURRDATETIME_TAG",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 0,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 43,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10043",
      ItemName: "1PRODUCT.PROCENT_1.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 44,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10044",
      ItemName: "2PRODUCT.BVR_SPEED.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 45,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10045",
      ItemName: "2PRODUCT.BNC_SPEED.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 46,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10046",
      ItemName: "5PRODUCT.BC1_SPEED.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 47,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10047",
      ItemName: "5PRODUCT.BC2_SPEED.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 48,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10048",
      ItemName: "5PRODUCT.BB_SPEED.OUT",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 2,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
    {
      $type:
        "Insight.DisplayFormats.Runtime.Persistence.GenericDataObjectConfiguration, Insight.DisplayFormats.Runtime",
      DataObjectId: 49,
      ServerBehaviors: 6,
      ParentDataObjectId: 2,
      Bindings: "10049",
      ItemName: "CURRDATETIME_TAG",
      Aggregate: "Snapshot",
      TagSourceName: "DefaultPHD",
      RawValueDecimalPlaces: 0,
      LowConfidenceThreshold: 100,
      DisplayValueParameterFormatString: "{0}",
      TooltipParameterFormatString: "{1}",
      AuxiliaryParameterFormatString: "{2}",
    },
  ],
};
